services:

    db:
        build:
            context: .
            dockerfile: ./postgres-pt_BR/Dockerfile
        container_name: postgresdb
        restart: always
        ports:
            - 5432:5432
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_USER: bravo
            POSTGRES_PASSWORD: bravo
            POSTGRES_DB: bravo
        volumes:
            - postgres_db:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis
        restart: always
        environment:
            TZ: America/Sao_Paulo
        ports:
            - 6379:6379
        volumes:
            - redis:/data

    bravo:
        build:
            context: ../
            dockerfile: deployments/bravo/Dockerfile
        container_name: bravo
        restart: always
        ports:
            - 8080:8080
        environment:
            TZ: America/Sao_Paulo
            BRAVO_DB: postgres://bravo:bravo@host.docker.internal:5432/bravo
            BRAVO_CACHE: redis://host.docker.internal:6379/0
            BRAVO_COIN_LAYER_KEY: 0b9bffd41dd007b05ee2e452ddbde803
            BRAVO_CURRENCY_LAYER_KEY: 8fc96429493d88318aff2b66efacf8cf
        volumes:
            - bravo:/app
        depends_on:
            - db
            - redis

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        ports:
            - 5050:80
        environment:
            TZ: America/Sao_Paulo
            PGADMIN_DEFAULT_EMAIL: aandrade1234@gmail.com
            PGADMIN_DEFAULT_PASSWORD: bravo
        volumes:
            - pgadmin4:/var/lib/pgadmin
            - pgadmin4:/pgadmin4/servers.json
        depends_on:
            - db

    fortio:
        build:
            context: .
            dockerfile: fortio/Dockerfile
        container_name: fortio
        restart: always
        ports:
            - 8088:8080
        environment:
            TZ: America/Sao_Paulo
        volumes:
            - fortio:/go
volumes:
    postgres_db:
    pgadmin4:
    redis:
    bravo:
    fortio: